import { NextResponse } from 'next/server';

import { studioConfig } from '@/lib/studio/config';
import { studioModules } from '@/lib/studio/modules';
import { systemCapabilities } from '@/lib/studio/types';

export async function GET() {
  const routes = [
    '/',
    '/about',
    '/studio',
    '/systems',
    '/generate',
    '/assets',
    '/jobs',
    '/pricing',
    '/contact',
    '/waitlist',
    '/privacy',
    '/terms',
    '/status',
    '/dashboard',
    '/settings',
    '/usage',
    '/analytics',
    '/integrations',
    '/asset-factory',
    '/motion',
    '/cinema',
    '/music',
    '/visuals',
    '/spatial',
    '/admin',
  ];

  const apiEndpoints = [
    '/api/health',
    '/api/system/health',
    '/api/system/manifest',
    '/api/system/capabilities',
    '/api/system/integration-contract',
    '/api/system/urai-contract',
    '/api/system/openapi',
    '/healthz',
    '/readyz',
  ];

  return NextResponse.json({
    ok: true,
    service: 'urai-studio',
    version: studioConfig.version ?? '1.0.0',
    domain: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.uraistudio.com',
    appRoot: 'apps/studio',
    environment: studioConfig.environment,
    routes,
    apiEndpoints,
    routeMap: Object.fromEntries(studioModules.map((module) => [module.id, module.route])),
    acceptedIntegrationIds: studioModules.map((module) => module.id),
    connectedSystems: studioModules.map((module) => ({
      id: module.id,
      name: module.name,
      route: module.route,
      status: module.status,
      requiredEnv: module.requiredEnv,
    })),
    moduleRegistry: studioModules,
    capabilities: systemCapabilities,
    authRequirements: {
      publicRoutes: [
        '/',
        '/about',
        '/studio',
        '/systems',
        '/generate',
        '/assets',
        '/jobs',
        '/pricing',
        '/contact',
        '/waitlist',
        '/privacy',
        '/terms',
        '/status',
      ],
      protectedRoutes: [
        '/dashboard',
        '/settings',
        '/usage',
        '/analytics',
        '/integrations',
        '/asset-factory',
        '/motion',
        '/cinema',
        '/music',
        '/visuals',
        '/spatial',
        '/admin',
      ],
      note: 'Public system routes are readable. Mutating production APIs and private data routes must be authenticated and tenant-scoped before live private data is exposed.',
    },
    environmentVariables: [
      'NEXT_PUBLIC_SITE_URL',
      'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
      'FIREBASE_PROJECT_ID',
      'FIREBASE_CLIENT_EMAIL',
      'FIREBASE_PRIVATE_KEY',
      'GOOGLE_APPLICATION_CREDENTIALS',
      'STUDIO_GENERATION_ENDPOINT',
      'STUDIO_GENERATION_API_KEY',
      'STRIPE_SECRET_KEY',
      'STRIPE_WEBHOOK_SECRET',
      'CRON_SECRET',
    ],
    assetHandoffModel: 'uri+metadata+jobId',
    statusModel: ['live', 'fallback', 'mock', 'disconnected'],
    jobLifecycle: ['intake', 'queued', 'rendering', 'materialized', 'published', 'approved', 'rollback'],
    assetLifecycle: ['requested', 'generated', 'stored', 'reviewed', 'published', 'archived'],
    healthEndpoint: '/api/system/health',
    healthGuarantees: [
      'safe JSON responses',
      'no secret exposure',
      'feature-gated unavailable services',
      'status warnings for disconnected integrations',
      'structured diagnostics for configured integrations and module status',
    ],
    smokeTestCoverage: routes.concat(apiEndpoints),
    deploymentTarget: 'Firebase Hosting, Firebase App Hosting, or Vercel for https://www.uraistudio.com',
    rollbackInstructions:
      'Revert the release branch or redeploy the previous verified Firebase Hosting/App Hosting/Vercel version.',
    breakingChangePolicy: 'semver-major-only',
    compatibilityNotes: 'Additive fields are backward compatible.',
    knownLimitations: [
      'Live deploy, Stripe checkout, private auth, and generation queue require production credentials and provider configuration.',
    ],
  });
}
