import { StudioModule } from './types';

const p = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
const moduleDef = (m: StudioModule) => m;

export const studioModules: StudioModule[] = [
moduleDef({id:'studio',name:'URAI Studio',description:'Central control surface for URAI systems.',route:'/studio',status:'fallback',healthEndpoint:'/api/system/health',firebaseProjectId:p,integrationType:'internal',enabled:true,requiredEnv:['NEXT_PUBLIC_FIREBASE_PROJECT_ID'],owner:'URAI Platform',surfaceCategory:'core',inputs:['module health','job metadata'],outputs:['orchestration decisions'],capabilities:['studio-dashboard','system-health'],fallbackBehavior:'Serve dashboard with diagnostics.',productionCritical:true}),
moduleDef({id:'asset-factory',name:'Asset Factory',description:'Generative asset orchestration bridge.',route:'/asset-factory',status:'disconnected',healthEndpoint:'/api/integrations/asset-factory/health',hostingUrl:process.env.NEXT_PUBLIC_ASSET_FACTORY_URL,integrationType:'hybrid',enabled:true,requiredEnv:['NEXT_PUBLIC_ASSET_FACTORY_URL|ASSET_FACTORY_INTERNAL_URL'],owner:'URAI Creative',surfaceCategory:'creative',inputs:['prompts','asset specs'],outputs:['assets','job events'],capabilities:['asset-factory-control'],fallbackBehavior:'Expose disconnected diagnostics; never fake success.',productionCritical:true}),
moduleDef({id:'spatial',name:'Spatial',description:'Spatial scene and world integration.',route:'/spatial',status:'fallback',hostingUrl:process.env.NEXT_PUBLIC_URAI_SPATIAL_URL,integrationType:'external',enabled:true,requiredEnv:['NEXT_PUBLIC_URAI_SPATIAL_URL'],owner:'URAI Spatial',surfaceCategory:'creative',inputs:['scene params'],outputs:['spatial assets'],capabilities:['spatial-integration'],fallbackBehavior:'Show contract and connection state.',productionCritical:true}),
...['motion','cinema','music','visuals','content'].map((id)=>moduleDef({id,name:id[0].toUpperCase()+id.slice(1),description:`${id} pipeline module`,route:`/${id}`,status:'fallback',integrationType:'internal',enabled:true,requiredEnv:[],owner:'URAI Creative',surfaceCategory:'creative',inputs:['asset refs','prompts'],outputs:[`${id} outputs`],capabilities:[`${id}-pipeline`],fallbackBehavior:'Render pipeline intent and hooks.',productionCritical:true})),
moduleDef({id:'marketing',name:'Marketing',description:'Marketing integration surface.',route:'/integrations',status:'fallback',hostingUrl:process.env.NEXT_PUBLIC_URAI_MARKETING_URL,integrationType:'external',enabled:true,requiredEnv:['NEXT_PUBLIC_URAI_MARKETING_URL'],owner:'URAI Growth',surfaceCategory:'operations',inputs:['campaign metrics'],outputs:['campaign actions'],capabilities:['integration-contract'],fallbackBehavior:'Show external link when configured.',productionCritical:false}),
moduleDef({id:'analytics',name:'Analytics',description:'Usage and analytics viewing.',route:'/analytics',status:'fallback',hostingUrl:process.env.NEXT_PUBLIC_URAI_ANALYTICS_URL,integrationType:'external',enabled:true,requiredEnv:['NEXT_PUBLIC_URAI_ANALYTICS_URL'],owner:'URAI Data',surfaceCategory:'operations',inputs:['event streams'],outputs:['reports'],capabilities:['analytics-view','usage-reporting'],fallbackBehavior:'Diagnostic-only if backend unavailable.',productionCritical:true}),
moduleDef({id:'admin',name:'Admin',description:'Admin and controls.',route:'/admin',status:'fallback',hostingUrl:process.env.NEXT_PUBLIC_URAI_ADMIN_URL,integrationType:'external',enabled:true,requiredEnv:['NEXT_PUBLIC_URAI_ADMIN_URL'],owner:'URAI Admin',surfaceCategory:'operations',inputs:['control actions'],outputs:['config updates'],capabilities:['admin-control'],fallbackBehavior:'Read-only diagnostics when disconnected.',productionCritical:true}),
moduleDef({id:'foundation',name:'Foundation',description:'Platform foundation and labs.',route:'/system',status:'fallback',integrationType:'internal',enabled:true,requiredEnv:[],owner:'URAI Foundation',surfaceCategory:'core',inputs:['system telemetry'],outputs:['platform strategy'],capabilities:['system-health'],fallbackBehavior:'Show contracts and warnings.',productionCritical:true}),
moduleDef({id:'jobs',name:'Jobs',description:'Job operations and queue diagnostics.',route:'/jobs',status:'fallback',integrationType:'internal',enabled:true,requiredEnv:[],owner:'URAI Ops',surfaceCategory:'operations',inputs:['queue jobs'],outputs:['job statuses'],capabilities:['usage-reporting'],fallbackBehavior:'Show no-live-source state if backend absent.',productionCritical:true}),
moduleDef({id:'privacy',name:'Privacy',description:'Privacy controls and disclosures.',route:'/settings',status:'fallback',hostingUrl:process.env.NEXT_PUBLIC_URAI_PRIVACY_URL,integrationType:'hybrid',enabled:true,requiredEnv:['NEXT_PUBLIC_URAI_PRIVACY_URL'],owner:'URAI Compliance',surfaceCategory:'operations',inputs:['policy settings'],outputs:['privacy policy links'],capabilities:['integration-contract'],fallbackBehavior:'Local diagnostics plus external policy link.',productionCritical:true}),
moduleDef({id:'investors',name:'Investors',description:'Investor-facing surface links.',route:'/dashboard',status:'fallback',hostingUrl:process.env.NEXT_PUBLIC_URAI_INVESTORS_URL,integrationType:'external',enabled:true,requiredEnv:['NEXT_PUBLIC_URAI_INVESTORS_URL'],owner:'URAI Leadership',surfaceCategory:'core',inputs:['kpis'],outputs:['readouts'],capabilities:['analytics-view'],fallbackBehavior:'Display unconfigured state safely.',productionCritical:false}),
];
export const moduleByRoute = Object.fromEntries(studioModules.map((m) => [m.route, m]));
