import type { StudioModule } from './types';

const firebaseProjectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;

function defineModule(module: StudioModule): StudioModule {
  return module;
}

const creativePipelineIds = ['motion', 'cinema', 'music', 'visuals', 'content'] as const;

type CreativePipelineId = (typeof creativePipelineIds)[number];

function titleCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function creativePipelineModule(id: CreativePipelineId): StudioModule {
  return defineModule({
    id,
    name: titleCase(id),
    description: `${id} pipeline module`,
    route: `/${id}`,
    status: 'fallback',
    integrationType: 'internal',
    enabled: true,
    requiredEnv: [],
    owner: 'URAI Creative',
    surfaceCategory: 'creative',
    inputs: ['asset refs', 'prompts'],
    outputs: [`${id} outputs`],
    capabilities: [`${id}-pipeline`],
    fallbackBehavior: 'Render pipeline intent and hooks.',
    productionCritical: true,
  });
}

export const studioModules: StudioModule[] = [
  defineModule({
    id: 'studio',
    name: 'URAI Studio',
    description: 'Central control surface for URAI systems.',
    route: '/studio',
    status: 'fallback',
    healthEndpoint: '/api/system/health',
    firebaseProjectId,
    integrationType: 'internal',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_FIREBASE_PROJECT_ID'],
    owner: 'URAI Platform',
    surfaceCategory: 'core',
    inputs: ['module health', 'job metadata'],
    outputs: ['orchestration decisions'],
    capabilities: ['studio-dashboard', 'system-health'],
    fallbackBehavior: 'Serve dashboard with diagnostics.',
    productionCritical: true,
  }),
  defineModule({
    id: 'asset-factory',
    name: 'Asset Factory',
    description: 'Generative asset orchestration bridge.',
    route: '/asset-factory',
    status: 'disconnected',
    healthEndpoint: '/api/integrations/asset-factory/health',
    hostingUrl: process.env.NEXT_PUBLIC_ASSET_FACTORY_URL,
    integrationType: 'hybrid',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_ASSET_FACTORY_URL|ASSET_FACTORY_INTERNAL_URL'],
    owner: 'URAI Creative',
    surfaceCategory: 'creative',
    inputs: ['prompts', 'asset specs'],
    outputs: ['assets', 'job events'],
    capabilities: ['asset-factory-control'],
    fallbackBehavior: 'Expose disconnected diagnostics; never fake success.',
    productionCritical: true,
  }),
  defineModule({
    id: 'spatial',
    name: 'Spatial',
    description: 'Spatial scene and world integration.',
    route: '/spatial',
    status: 'fallback',
    hostingUrl: process.env.NEXT_PUBLIC_URAI_SPATIAL_URL,
    integrationType: 'external',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_URAI_SPATIAL_URL'],
    owner: 'URAI Spatial',
    surfaceCategory: 'creative',
    inputs: ['scene params'],
    outputs: ['spatial assets'],
    capabilities: ['spatial-integration'],
    fallbackBehavior: 'Show contract and connection state.',
    productionCritical: true,
  }),
  ...creativePipelineIds.map(creativePipelineModule),
  defineModule({
    id: 'marketing',
    name: 'Marketing',
    description: 'Marketing integration surface.',
    route: '/integrations',
    status: 'fallback',
    hostingUrl: process.env.NEXT_PUBLIC_URAI_MARKETING_URL,
    integrationType: 'external',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_URAI_MARKETING_URL'],
    owner: 'URAI Growth',
    surfaceCategory: 'operations',
    inputs: ['campaign metrics'],
    outputs: ['campaign actions'],
    capabilities: ['integration-contract'],
    fallbackBehavior: 'Show external link when configured.',
    productionCritical: false,
  }),
  defineModule({
    id: 'analytics',
    name: 'Analytics',
    description: 'Usage and analytics viewing.',
    route: '/analytics',
    status: 'fallback',
    hostingUrl: process.env.NEXT_PUBLIC_URAI_ANALYTICS_URL,
    integrationType: 'external',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_URAI_ANALYTICS_URL'],
    owner: 'URAI Data',
    surfaceCategory: 'operations',
    inputs: ['event streams'],
    outputs: ['reports'],
    capabilities: ['analytics-view', 'usage-reporting'],
    fallbackBehavior: 'Diagnostic-only if backend unavailable.',
    productionCritical: true,
  }),
  defineModule({
    id: 'admin',
    name: 'Admin',
    description: 'Gated admin surface for operator-only diagnostics and configuration state.',
    route: '/admin',
    status: 'fallback',
    hostingUrl: process.env.NEXT_PUBLIC_URAI_ADMIN_URL,
    integrationType: 'external',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_URAI_ADMIN_URL'],
    owner: 'URAI Admin',
    surfaceCategory: 'operations',
    inputs: ['gated diagnostics', 'operator review'],
    outputs: ['read-only status', 'configuration posture'],
    capabilities: ['admin-control'],
    fallbackBehavior: 'Show gated public-demo state unless admin QA is explicitly enabled.',
    productionCritical: true,
  }),
  defineModule({
    id: 'foundation',
    name: 'Foundation',
    description: 'Platform foundation and labs.',
    route: '/system',
    status: 'fallback',
    integrationType: 'internal',
    enabled: true,
    requiredEnv: [],
    owner: 'URAI Foundation',
    surfaceCategory: 'core',
    inputs: ['system telemetry'],
    outputs: ['platform strategy'],
    capabilities: ['system-health'],
    fallbackBehavior: 'Show contracts and warnings.',
    productionCritical: true,
  }),
  defineModule({
    id: 'jobs',
    name: 'Jobs',
    description: 'Job operations and queue diagnostics.',
    route: '/jobs',
    status: 'fallback',
    integrationType: 'internal',
    enabled: true,
    requiredEnv: [],
    owner: 'URAI Ops',
    surfaceCategory: 'operations',
    inputs: ['queue jobs'],
    outputs: ['job statuses'],
    capabilities: ['usage-reporting'],
    fallbackBehavior: 'Show no-live-source state if backend absent.',
    productionCritical: true,
  }),
  defineModule({
    id: 'privacy',
    name: 'Privacy',
    description: 'Privacy controls and disclosures.',
    route: '/settings',
    status: 'fallback',
    hostingUrl: process.env.NEXT_PUBLIC_URAI_PRIVACY_URL,
    integrationType: 'hybrid',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_URAI_PRIVACY_URL'],
    owner: 'URAI Compliance',
    surfaceCategory: 'operations',
    inputs: ['policy settings'],
    outputs: ['privacy policy links'],
    capabilities: ['integration-contract'],
    fallbackBehavior: 'Local diagnostics plus external policy link.',
    productionCritical: true,
  }),
  defineModule({
    id: 'investors',
    name: 'Investors',
    description: 'Investor-facing surface links.',
    route: '/dashboard',
    status: 'fallback',
    hostingUrl: process.env.NEXT_PUBLIC_URAI_INVESTORS_URL,
    integrationType: 'external',
    enabled: true,
    requiredEnv: ['NEXT_PUBLIC_URAI_INVESTORS_URL'],
    owner: 'URAI Leadership',
    surfaceCategory: 'core',
    inputs: ['kpis'],
    outputs: ['readouts'],
    capabilities: ['analytics-view'],
    fallbackBehavior: 'Display unconfigured state safely.',
    productionCritical: false,
  }),
];

export const moduleByRoute: Record<string, StudioModule> = Object.fromEntries(
  studioModules.map((module) => [module.route, module]),
);