'use client';

import { useState } from 'react';

import { hasFirebaseClientConfig, studioApi } from '@/lib/studio/firebase-client';

type ActionStatus = 'idle' | 'running' | 'success' | 'error';

type ActionState = {
  status: ActionStatus;
  message: string;
  payload?: unknown;
};

const initialState: ActionState = {
  status: 'idle',
  message: 'Choose an action to verify the Studio system flow.',
};

function getExportJobId(result: unknown): string {
  if (typeof result !== 'object' || result === null || !('exportJobId' in result)) return '';
  const exportJobId = (result as { exportJobId?: unknown }).exportJobId;
  return typeof exportJobId === 'string' ? exportJobId : '';
}

function renderPayload(payload: unknown): string {
  try {
    return JSON.stringify(payload, null, 2);
  } catch {
    return String(payload);
  }
}

export function StudioActionPanel() {
  const [state, setState] = useState<ActionState>(initialState);
  const [latestExportJobId, setLatestExportJobId] = useState<string>('');

  async function run(label: string, action: () => Promise<unknown>) {
    setState({ status: 'running', message: `${label} is running...` });
    try {
      const result = await action();
      const exportJobId = getExportJobId(result);
      if (exportJobId) setLatestExportJobId(exportJobId);
      setState({ status: 'success', message: `${label} completed.`, payload: result });
    } catch (error) {
      setState({
        status: 'error',
        message: error instanceof Error ? error.message : `${label} failed with an unknown error.`,
      });
    }
  }

  const configured = hasFirebaseClientConfig();
  const statusClassName = `card status-${state.status}`;

  return (
    <section className="section-panel" aria-label="URAI Studio live action panel">
      <div className="section-heading">
        <p className="eyebrow">Live system actions</p>
        <h2>Callable verification panel</h2>
        <p>
          These controls call the Firebase callable layer when Firebase client config is present. Without config,
          they intentionally fail with a clear setup message instead of pretending the system is live.
        </p>
      </div>

      <div className="grid three">
        <article className="card">
          <p className="eyebrow">Firebase client</p>
          <h3>{configured ? 'Configured' : 'Missing config'}</h3>
          <p>{configured ? 'NEXT_PUBLIC_FIREBASE_* values are present.' : 'Add NEXT_PUBLIC_FIREBASE_* values to enable live actions.'}</p>
        </article>
        <article className="card">
          <p className="eyebrow">Latest export job</p>
          <h3>{latestExportJobId || 'None yet'}</h3>
          <p>Generated by create export or demo seed actions during this browser session.</p>
        </article>
        <article className={statusClassName}>
          <p className="eyebrow">Last action</p>
          <h3>{state.status}</h3>
          <p>{state.message}</p>
        </article>
      </div>

      <div className="cta-row" aria-label="Callable actions">
        <button className="button button-secondary" type="button" disabled={state.status === 'running'} onClick={() => run('Ping', () => studioApi.ping())}>
          Ping Functions
        </button>
        <button className="button button-primary" type="button" disabled={state.status === 'running'} onClick={() => run('Seed demo', () => studioApi.seedStudioDemo())}>
          Seed Demo Project
        </button>
        <button
          className="button button-secondary"
          type="button"
          disabled={state.status === 'running'}
          onClick={() => run('Create project', () => studioApi.createStudioProject({ title: 'URAI Studio Browser Project', mode: 'user' }))}
        >
          Create Project
        </button>
        <button
          className="button button-secondary"
          type="button"
          disabled={state.status === 'running'}
          onClick={() => run('Generate script', () => studioApi.generateStudioScript({ prompt: 'Create a short launch narration for URAI Studio.' }))}
        >
          Generate Script
        </button>
        <button
          className="button button-secondary"
          type="button"
          disabled={state.status === 'running'}
          onClick={() => run('Create asset job', () => studioApi.createAssetJob({ type: 'image', prompt: 'Cinematic aura-lit Studio asset.' }))}
        >
          Create Asset Job
        </button>
        <button
          className="button button-secondary"
          type="button"
          disabled={state.status === 'running'}
          onClick={() => run('Create export job', () => studioApi.createExportJob({ type: 'manifest' }))}
        >
          Create Export Job
        </button>
        <button
          className="button button-secondary"
          type="button"
          disabled={!latestExportJobId || state.status === 'running'}
          onClick={() => run('Process export job', () => studioApi.processExportJob({ exportJobId: latestExportJobId }))}
        >
          Process Export Job
        </button>
        <button
          className="button button-secondary"
          type="button"
          disabled={state.status === 'running'}
          onClick={() => run('Load dashboard', () => studioApi.getStudioDashboard())}
        >
          Load Dashboard
        </button>
      </div>

      {state.payload !== undefined ? (
        <pre className="card code-block" aria-label="Callable response payload">
          {renderPayload(state.payload)}
        </pre>
      ) : null}
    </section>
  );
}
